categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads Galaxy's JSON data source tool command.
long_description: |
  Galaxy's JSON data source tool command
name: package_galaxy_json_data_source
owner: blankenberg
remote_repository_url: https://github.com/blankenberg/galaxy-tools-blankenberg/tree/master/packages/package_galaxy_json_data_source
type: tool_dependency_definition
